export const airSamples = {
  slug: "air-samples",
  label: "Air samples",
  endpoint: "/api/admin/air-samples",
  rowKey: "air_sample_id",
  description: "One lab-issued slide per sample location. Rolls up the fungal + particulate counts and notable objects.",
  columns: [
    { key: "air_sample_id",        label: "ID",            mono: true, width: 60 },
    { key: "sample_location_id",   label: "Location",      mono: true, width: 90 },
    { key: "lab_partner",          label: "Lab",           cell: "badge" },
    { key: "lab_sample_id",        label: "Lab sample ID", mono: true, muted: true },
    { key: "air_volume_litres",    label: "Vol (L)",       mono: true, align: "right", width: 80 },
    { key: "total_spores_per_m3",  label: "Total / m³",    mono: true, align: "right", width: 100 },
    { key: "dominant_fungal_classification_id", label: "Dominant", mono: true, width: 90 },
    { key: "sampled_at",           label: "Sampled",       cell: "datetime" },
    { key: "received_by_lab_at",   label: "Received",      cell: "datetime", muted: true },
    { key: "reported_by_lab_at",   label: "Reported",      cell: "datetime", muted: true },
    { key: "lab_pdf_storage_path", label: "Lab PDF",       mono: true, muted: true },
  ],
};
