export const inspections = {
  slug: "inspections",
  label: "Inspections",
  endpoint: "/api/admin/inspections",
  rowKey: "inspection_id",
  description: "Scheduled / completed diagnostic visits. Carries the report fields directly.",
  embeds: [
    "customers(name)",
    "properties(address_line, postcode)",
    "technician:technicians!inspections_technician_id_fkey(name, role)",
    "signoff:technicians!inspections_signed_off_by_technician_id_fkey(name, role)",
  ],
  columns: [
    { key: "inspection_id",            label: "ID",          mono: true, width: 60 },
    { key: "customer_id",              label: "Customer",    lookup: ["customers", "name"] },
    { key: "property_id",              label: "Property",    lookup: ["properties", "address_line"] },
    { key: "scheduled_at",             label: "Scheduled",   cell: "datetime" },
    { key: "status",                   label: "Status",      cell: "badge" },
    { key: "inspection_type",          label: "Type",        cell: "badge" },
    { key: "technician_id",            label: "Technician",  lookup: ["technician", "name"] },
    { key: "signed_off_by_technician_id", label: "Signed off by", lookup: ["signoff", "name"] },
    { key: "signed_off_at",            label: "Signed off",  cell: "datetime" },
    { key: "report_status",            label: "Report",      cell: "badge" },
    { key: "report_severity",          label: "Severity",    cell: "badge" },
    { key: "amount_paid",              label: "Paid",        cell: "currency", align: "right" },
    { key: "cal_booking_id",           label: "Cal ID",      mono: true, muted: true },
    { key: "stripe_payment_intent_id", label: "Stripe PI",   mono: true, muted: true },
    { key: "report_slug",              label: "Report slug", mono: true, muted: true },
  ],
};
