import { notFound } from "next/navigation";
import { createServerSupabaseClient } from "../../../../lib/supabase";
import PrintViewer from "./PrintViewer";
import { resolveTemplate } from "./templates";
import "./print.css";

// Public-facing PDF viewer page. Shows the generated PDF inside an iframe
// (Docusign-style preview), with a toolbar to switch between the three
// audience templates (homeowner / tenant / insurance) and a Download
// button. The PDF itself is generated by /r2/[slug]/print/pdf via
// Puppeteer against the dedicated paper-first render route — this page
// just embeds it.

export const dynamic = "force-dynamic";

export async function generateMetadata({ params }) {
  const { slug } = await params;
  return {
    title: `Sporetrust report — PDF · ${slug.slice(0, 8)}`,
    robots: { index: false, follow: false },
  };
}

export default async function ReportPrintViewerPage({ params, searchParams }) {
  const { slug } = await params;
  const sp = (await searchParams) || {};
  const template = resolveTemplate(typeof sp.template === "string" ? sp.template : null);

  // Lightweight existence check — we don't need the full inspection
  // payload for the viewer, just enough to know the report exists and is
  // published. If not, 404. The render route does the real fetch when
  // Puppeteer hits it.
  const supabase = createServerSupabaseClient();
  if (!supabase) notFound();
  const { data, error } = await supabase
    .from("inspections")
    .select("inspection_id, report_title, properties(address_line)")
    .eq("report_slug", slug)
    .eq("report_status", "published")
    .maybeSingle();
  if (error || !data) notFound();

  return (
    <PrintViewer
      slug={slug}
      template={template.id}
      reportTitle={data.report_title || "Inspection report"}
      addressLine={data.properties?.address_line || ""}
    />
  );
}
