// Generate supabase/seed.sql from lib/admin/mockData.js.
// Run: node scripts/generate-seed.mjs
// Then: psql "$SUPABASE_DB_URL" -f supabase/seed.sql

import { writeFileSync } from "node:fs";
import { mockData } from "../lib/admin/mockData.js";

// Topological order: parents first, children second.
const ORDER = [
  "trade-categories",
  "fungal-classifications",
  "particulate-types",
  "equipment-types",
  "technicians",
  "technician-equipment",
  "customers",
  "properties",
  "inspections",
  "inspection-equipment",
  "sample-locations",
  "image-captures",
  "moisture-readings",
  "location-findings",
  "location-sources",
  "air-samples",
  "air-sample-fungal-counts",
  "air-sample-particulate-counts",
  "air-sample-notable-objects",
  "scope-items",
  "partner-organizations",
  "partner-skills",
  "partner-handoffs",
  "subscriptions",
];

// Slug → table identity column. partner-skills + inspection-equipment have
// composite PKs and no identity.
const IDENTITY_COL = {
  customers: "customer_id",
  properties: "property_id",
  inspections: "inspection_id",
  "sample-locations": "sample_location_id",
  "image-captures": "image_capture_id",
  "moisture-readings": "moisture_reading_id",
  "location-findings": "finding_id",
  "location-sources": "source_id",
  "air-samples": "air_sample_id",
  "air-sample-fungal-counts": "air_sample_fungal_count_id",
  "air-sample-particulate-counts": "air_sample_particulate_count_id",
  "air-sample-notable-objects": "notable_object_id",
  "scope-items": "scope_item_id",
  "partner-organizations": "partner_id",
  "partner-handoffs": "handoff_id",
  subscriptions: "subscription_id",
  "trade-categories": "trade_category_id",
  "fungal-classifications": "fungal_classification_id",
  "particulate-types": "particulate_type_id",
  technicians: "technician_id",
  "equipment-types": "equipment_type_id",
  "technician-equipment": "technician_equipment_id",
};

const tableFor = (slug) => slug.replace(/-/g, "_");

function escapeLiteral(v) {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
  if (typeof v === "number") return String(v);
  if (Array.isArray(v)) {
    const inner = v.map((x) => `'${String(x).replace(/'/g, "''")}'`).join(",");
    return `ARRAY[${inner}]::TEXT[]`;
  }
  if (typeof v === "string") return `'${v.replace(/'/g, "''")}'`;
  return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
}

let sql = `-- Auto-generated by scripts/generate-seed.mjs — do NOT edit by hand.
-- Mock data from lib/admin/mockData.js, shaped to schema.sql.
-- Apply: psql "$SUPABASE_DB_URL" -f supabase/seed.sql

BEGIN;

-- Wipe in reverse-FK order so the seed is idempotent.
`;

for (const slug of [...ORDER].reverse()) {
  sql += `TRUNCATE TABLE ${tableFor(slug)} RESTART IDENTITY CASCADE;\n`;
}
sql += "\n";

for (const slug of ORDER) {
  const rows = mockData[slug] || [];
  if (rows.length === 0) continue;
  const table = tableFor(slug);
  const hasIdentity = Boolean(IDENTITY_COL[slug]);

  // Strip any UI-only pseudo-key.
  const cols = Object.keys(rows[0]).filter((k) => k !== "rowid");

  sql += `-- ${table} (${rows.length} row${rows.length === 1 ? "" : "s"})\n`;
  for (const row of rows) {
    const values = cols.map((c) => escapeLiteral(row[c]));
    const sysOverride = hasIdentity ? " OVERRIDING SYSTEM VALUE" : "";
    sql += `INSERT INTO ${table} (${cols.join(", ")})${sysOverride} VALUES (${values.join(", ")});\n`;
  }
  sql += "\n";
}

sql += "-- Bump identity sequences past the inserted max so future inserts don't collide.\n";
for (const [slug, col] of Object.entries(IDENTITY_COL)) {
  const table = tableFor(slug);
  sql += `SELECT setval(pg_get_serial_sequence('${table}', '${col}'), COALESCE((SELECT MAX(${col}) FROM ${table}), 0) + 1, false);\n`;
}

sql += "\nCOMMIT;\n";

const outPath = new URL("../supabase/seed.sql", import.meta.url);
writeFileSync(outPath, sql);
console.log(`Wrote ${outPath.pathname}`);
console.log(`Tables seeded: ${ORDER.length}`);
console.log(`Total rows:    ${ORDER.reduce((sum, s) => sum + (mockData[s]?.length ?? 0), 0)}`);
